-- =====================================
-- MIGRATION: update schema for inventory
-- =====================================

-- 1) Add serial_number to input_barang
alter table input_barang
  add column if not exists serial_number text;

create index if not exists idx_input_barang_serial on input_barang(serial_number);

-- 2) Create master peminjam table
create table if not exists tbl_peminjam (
  no bigint generated by default as identity primary key,
  nim text not null,
  nama text not null,
  prodi text not null,
  telepon text not null
);

create index if not exists idx_peminjam_nim on tbl_peminjam(nim);

-- 3) Enable RLS
alter table tbl_peminjam enable row level security;

-- 4) RLS policies for tbl_peminjam
create policy "allow authenticated read peminjam"
on tbl_peminjam for select
to authenticated
using (true);

create policy "allow authenticated write peminjam"
on tbl_peminjam for insert
to authenticated
with check (true);

create policy "allow authenticated update peminjam"
on tbl_peminjam for update
to authenticated
using (true);

create policy "allow authenticated delete peminjam"
on tbl_peminjam for delete
to authenticated
using (true);
